development:
  adapter: mysql2
  hostname: localhost
  encoding: utf8
  reconnect: false
  database: first_app_development
  pool: 10
  username: root
  password:

test:
  adapter: mysql2
  hostname: localhost
  encoding: utf8
  reconnect: false
  database: first_app_test
  pool: 10
  username: root
  password:

production:
  hostname: localhost
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: first_app_production
  pool: 10
  username: root
  password:
